### ISSUE TITLE
`libp2p-daemon` package is completely broken

### ISSUE THREAD

**Issue by pleerock** [libp2p/js-libp2p-daemon#158]
Start with the fresh installation:

1. `npm i @libp2p/daemon`
2. `jsp2pd --help`

You'll have the following error:

```shell
./node_modules/.bin/jsp2pd --help
TypeError: parser.yargs.option is not a function
```

and BTW the only test you have in the test cases of this project is [skipped](/libp2p-daemon/test/cli.spec.ts#L7).

Okay, I also found [this](https://github.com/libp2p/js-libp2p-daemon/blob/master/packages/libp2p-daemon/src/index.ts#L129). Whaat the ...? Maybe update project README and tell it's not working at all? Imagine how confusing such things for the users.

**Comment by p-shahi** [comment]
Hi @pleerock , you're right but this should be fixed by: https://github.com/libp2p/js-libp2p-daemon/pull/127
Closing this in favor of that PR
